export const reviews = [
  {
    id: 1,
    name: 'Sarah M.',
    city: 'New York City',
    rating: 5,
    text: "I've tried several cleaning services in Manhattan and AlphaLux is in a completely different league. My apartment has never looked this good. They're thorough, professional, and always on time.",
  },
  {
    id: 2,
    name: 'James T.',
    city: 'Long Island',
    rating: 5,
    text: "We use AlphaLux for biweekly cleaning and our house always feels like a model home when they're done. The team is friendly and respectful of our space. Highly recommend.",
  },
  {
    id: 3,
    name: 'Linda R.',
    city: 'Newark, NJ',
    rating: 5,
    text: "I hired AlphaLux for a move-out clean on my rental property and they exceeded every expectation. The unit looked better than when it was brand new. My tenants were thrilled.",
  },
  {
    id: 4,
    name: 'David K.',
    city: 'Hartford, CT',
    rating: 5,
    text: 'Our office has never been cleaner. AlphaLux handles our commercial cleaning three nights a week and they are incredibly consistent. No complaints whatsoever.',
  },
  {
    id: 5,
    name: 'Maria G.',
    city: 'Syracuse, NY',
    rating: 5,
    text: 'After our kitchen renovation, we called AlphaLux for post-construction cleaning. They removed every trace of dust and debris. It was like the construction never happened.',
  },
  {
    id: 6,
    name: 'Robert P.',
    city: 'New Haven, CT',
    rating: 5,
    text: "I manage several Airbnb properties near Yale and AlphaLux handles all my turnovers. Fast, reliable, and my guests consistently mention how clean the space is in their reviews.",
  },
  {
    id: 7,
    name: 'Angela W.',
    city: 'Buffalo, NY',
    rating: 5,
    text: "Finding a cleaning service in Buffalo that actually shows up and does quality work was a challenge until we found AlphaLux. They've been cleaning our home monthly for six months and every visit is fantastic.",
  },
  {
    id: 8,
    name: 'Tom H.',
    city: 'Danbury, CT',
    rating: 5,
    text: 'We needed a deep clean before hosting Thanksgiving and AlphaLux delivered big time. Every room was spotless. The team was professional and finished ahead of schedule.',
  },
]
